### ISSUE TITLE
Can this model be tested on arbitrary size image?

### ISSUE THREAD

**Issue by iris112358** [ningyu1991/TextureMixer#4]
Hi,

Thanks for open-sourcing this awesome work. The provided pre-trained model seems only accept a 128*128 image as input, is there any way to apply it onto an arbitrary sized image?

Thanks!

**Comment by ningyu1991** [comment]
Yes, the input image size to the pre-trained model has to be 128*128. If your texture image is spatially stationary, you can crop it to 128*128. Otherwise, you have to resize it to 128x128, or re-train your own model with a different input size.
